import type { GetServerSideProps } from "next";
import Head from "next/head";

import { cookieExists } from "@/lib/cookieExists";

import { Group } from "@/app/home/Group";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const userCookie = cookieExists("user.token", context);

  if (!userCookie) {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
      props: {},
    };
  }

  return {
    props: {},
  };
};

export default function GroupPage() {
  return (
    <>
      <Head>
        <title>Task Genius | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Group />
    </>
  );
}
